### ISSUE TITLE
Express Setup Checklist

### ISSUE THREAD

**Issue by bonniepeters** [bonniepeters/Seattle-Bucket-List#1]
# Express Checklist

## Setup

- [x] Make a directory for the project
- [x] Run `npm init` to initialize a Node project in the directory
- [x] `npm install express`
- [x] `npm install hbs`
- [x] Create your directory structure `mkdir db models views controllers`
- [x] Create `index.js`
- [x] Require Express in `index.js`: `const express = require('express')`
- [x] Require Handlebars in `index.js`: `const hbs = require('hbs')`
- [x] Create an instance of an express app: `const app = express()`
- [x] Set your view engine to handlebars: `app.set("view engine", "hbs")`
- [x] Make your app listen on a certain port: `app.listen(3000, () => console.log("Running on port 3000!"))`
- [x] Create your `layout.hbs` with an HTML scaffold, and any information you want on each page:
```js
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  {{{ body }}}
</body>
</html>
```

## Connect to MongoDB

- [x] `npm install mongoose`
- [x] Create a `connection.js` file in the `db/` directory
- [x] Require mongoose in the `connection` file
- [x] Connect to your database: `mongoose.connect('mongodb://localhost/db_name')`
- [x] Set the promise library: `mongoose.Promise = Promise` if you are using an older Mongoose version than v5.
- [x] Export your setup mongoose: `module.exports = mongoose`

## Define a Schema + Model

- [x] Create a file with your model's name in `models/`
- [x] Import mongoose from your connection file: `const mongoose = require("../db/connection")`
- [x] Create your schema and set it to a variable.
```js
const mySchema = new mongoose.Schema({
  field: DataType,
})
```
- [x] Create a model with your schema: `const myModel = mongoose.model("modelName", mySchema)`
- [x] Export your model: `module.exports = myModel`

## Seed your DataBase

- [x] Create `db/seed.js`
- [x] Import your schema from your model file: `const myModel = require('../models/myModel')`
- [x] Create your seed data in JSON format in `db/seeds.json`
- [x] Import your seed data into your `seeds.js` file: `const seedData = require("./seeds.json")`
- [x] Remove all of the items currently in your database: `myModel.remove({})`
- [x] Insert your seeds into your database within the `.then` method.
- [x] Exit the seeding process in another `.then` method.
```js
myModel.remove({})
  .then(() => {
    return myModel.collection.insert(seedData)
  })
  .then(() => {
    process.exit()
  })
```
- [x] Run your seed file in the terminal: `$ node db/seed.js`
- [x] Check to see if the items were inserted using the Mongo CLI.
  - [x] Run `$ mongo` to enter the Mongo CLI
  - [x] Run `> use my_database` and `db.my_collection.find()` to see your items

## Set Up your Controller

- [x] Create a controller file: `controllers/myItems.js`
- [x] Require your controller in `index.js`: `const myController = require('./controllers/myController')`
- [x] Use your controller **below any other configuration**: `app.use("/myUrlPrefix", myControllerController)`
- [x] Require Express in your controller file: `const express = require("express")`
- [x] Create a router instance in your controller file: `const router = express.Router()`
- [x] Import your model: `const myModel = require('../models/myModel')`
- [x] Export your router instance at the very bottom of the file: `module.exports = router`

## Create your Index Route

- [x] Setup a GET handler for the '/' route: `router.get("/", (req, res) => {})`
- [x] In the body of the GET handler, find all of the instances of your model: `myModel.find({})`
- [x] Once the items are returned from your database, render your index view: `res.render('index', { myInstances })`
```js
router.get("/", (req, res) => {
  myModel.find({}).then(myInstances => res.render('index', { myInstances }))
})
```
- [x] Create your view file: `views/index.hbs`
- [x] Create your view template with Handlebars:
```hbs
<h1>myModel</h1>

<ul>
  {{#each myInstances as |myInstance|}}
    <li>
      {{myInstance.attribute}}
    </li>
  {{/each}}
</ul>
```

## Create your Show Route

- [x] Setup a GET handler for the '/:id' route: `router.get("/:id", (req, res) => {})`
- [x] In the body of the GET handler, find an instance of your model: `myModel.findOne({ _id: req.params.id })`
- [x] Once the items are returned from your database, render your index view: `res.render('show', { myInstance })`
```js
router.get("/:id", (req, res) => {
  myModel.findOne({ _id: req.params.id }).then(myInstance => res.render('show', { myInstance }))
})
```
- [x] Create your view file: `views/show.hbs`
- [x] Create your view template with Handlebars:
```hbs
<h1>myModel</h1>

<h2>{{ myInstance.attribute }}</h2>
```

## Create your New Route

- [x] Setup a GET handler to display the form at '/new' route: `router.get("/:id", (req, res) => {})` **note: put this above your `/:id` route!**
```js
router.get('/new', (req, res) => {
  res.render('new')
})
```
- [x] Install body-parser: `$ npm install body-parser`
- [x] Require body-parser in your `index.js`: `const parser = require('body-parser')`
- [x] Setup body-parser in your `index.js`: `const parser = app.use(parser.urlencoded({ extended: true }))` **note: put this above where you `use` your controllers!**
- [x] Create your view file for your form: `views/new.hbs`
- [x] Create your view template with Handlebars:
```html
<h2>New Instance:</h2>

<form action="/" method="post" accept-charset="utf-8">
  <p>
    <label>myField:</label>
    <input type="text" name="myField"/>
  </p>
  <input type="submit" value="Create" />
</form>
```
- [x] Setup a POST handler for your post reqest to create a new item at url `/`: `router.post("/", (req, res) => {})`
- [x] In the body of the POST handler, create an instance of your model with the data from the form: `myModel.create(req.body)`
- [x] Once the items are returned from your database, redirect to your home page: `res.redirect('/')`
```js
router.post('/', (req, res) => {
  myModel.create(req.body)
    .then(myNewItem => {
      res.redirect('/')
    })
})
```

## Create your Update Route

- [x] Install method-override: `$ npm install method-override`
- [x] Require `method-override` in your `index.js`: `const methodOverride = require('method-override')`
- [x] Set up `method-override` in your `index.js`: `app.use(methodOverride('_method'))` **note: make sure this is above where you use your controller!**
- [x] Create a route to render your `edit` form: `router.get('/edit/:id', (req, res) => {})`
- [x] Find the item you want to edit in your database: `myModel.findOne({_id: req.params.id})`
- [x] Render the form: `res.render('edit', { myInstance })`
```js
router.get('/edit/:id', (req, res) => {
  myModel.findOne({_id: req.params.id})
    .then(instance => {
      res.render("edit", { myInstance })
    })
})
```
- [x] Create a form using handlebars for editing your item in `edit.hbs`
```hbs
<h2>Edit Item:</h2>

<form action="/{{myInstance.id}}?_method=put" method="post">
  <p>
    <label>Attribute:</label>
    <input type="text" value="{{myInstance.attribute}}" name="attribute"/>
  </p>
  <input type="submit" value="Update" />
</form>

```
- [x] Create a route to edit the item in the database: `router.put('/:id', (req, res) => {})`
- [x] Find an item in the database and edit it: `myModel.findOneandUpdate({_id: req.params.id}, req.body, { new: true })`
- [x] Redirect to the home page: `res.redirect('/')`
```js
router.put('/:id', (req, res) => {
  myModel.findOneAndUpdate({_id: req.params.id}, req.body, { new: true })
    .then(myInstance => {
      res.redirect('/')
    })
})
```

## Create your Delete Route

- [x] Create your delete route: `router.delete(':id', (req, res) => {})`
- [x] Remove the item from the database: `myModel.findOneAndRemove({ _id: req.params.id })`
- [x] Redirect to the home page: `res.redirect('/')`
```js
router.delete('/:id', (req, res) => {
  myModel.findOneAndRemove({ _id: req.params.id })
    .then(() => {
      res.redirect('/')
    })
})
```
- [x] Add a form to delete your item in `edit.hbs`
```hbs
<form action="/{{myInstance.id}}?_method=delete" method="post">
  <input type="submit" value="Remove">
</form>
```

### Bonus: Set up CSS

- [x] Create a `public/` folder with a `css/` subdirectory within it
- [x] Create a `styles.css` file within `/public/css` and add your styling
- [x] Host your `public/` folder: `app.use('/assets', express.static('public'))`
- [x] Include your CSS in the head of your `views/layout.hbs` file: `<link rel="stylesheet" href="/assets/css/styles.css" />`

### Read More!

* [Lesson Plan](https://git.generalassemb.ly/ga-wdi-lessons/express-mongoose)
* [ToDo App](https://git.generalassemb.ly/ga-wdi-exercises/express-to-do/tree/solution)
* [WhenPresident App](https://git.generalassemb.ly/ga-wdi-exercises/whenpresident/tree/express-mongoose-solution)
